### ISSUE TITLE
3.1 - First Website -- Alec Martin

### ISSUE THREAD

**Issue by captainclutch96** [tiy-indianapolis-ror-june2015/assignments#100]
Requirements
- Using the image and HTML & CSS templates provided, recreate the image with markup & styles.
- Use the images/folder for your used images

Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called 3.1-First-Website
- [x] Create a branch on 3.1-First-Website called dev
- [x] In Github, open a PR from dev into master
- [x] Port the images
  - [x] Checkpoint: index.html file created
  - [x] Checkpoint: styles.css file created
  - [x] Checkpoint: acquire relevant images & place within images/ folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [x] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code

**Comment by captainclutch96** [comment]
https://github.com/captainclutch96/3.1-First-Website

**Comment by dummied** [comment]
Broken images at the moment.

**Comment by captainclutch96** [comment]
https://github.com/captainclutch96/3.1-First-Website/pull/2

Yep, sorry about that, had the wrong file extensions for the images. This should work.

**Comment by captainclutch96** [comment]
https://github.com/captainclutch96/3.1-First-Website

Oops...wrong link. Lol. Sorry. It's late.

**Comment by captainclutch96** [comment]
Noticed the pictures were screwy, so I cleaned them up a bit.

https://github.com/captainclutch96/3.1-First-Website
