### ISSUE TITLE
3.2 - Responsivize -- Joe Bykowski

### ISSUE THREAD

**Issue by jbykowski** [tiy-indianapolis-ror-june2015/assignments#113]
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.2-Responsivize`
- [x] Create a branch on `3.2-Responsivize` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Adjust the website
  - [x] Checkpoint: Added full-height/width background image at any resolution to header/title section
  - [x] Checkpoint: top sections of each half (only when halved) line up accordingly
  - [x] Checkpoint: 2 images added throughout the content
  - [x] Checkpoint: used responsive web design to redefine page elements when the page is `600px` wide or below
  - [x] Checkpoint: validated the page doesn't look like crap
  - [x] Complete: pushed all relevant code

**Comment by jbykowski** [comment]
https://github.com/jbykowski/3.2-Responsivize/pull/1

**Comment by dummied** [comment]
Joe, when resized, it currently doesn't fill the full width.

**Comment by dummied** [comment]
Also: _Love_ the images.

**Comment by jbykowski** [comment]
Got it fixed!

https://github.com/jbykowski/3.2-Responsivize/commit/b8062e3dc7269ce455d4db92e0e7a42a48fca3a9
