### ISSUE TITLE
Week 6, Day 1 - moar reddit - Caleb Francis

### ISSUE THREAD

**Issue by calebonesimus** [tiy-indianapolis-ror-june2015/assignments#208]
https://github.com/calebonesimus/conde_nasty/pull/4

http://conde-nasty.herokuapp.com/

**Comment by calebonesimus** [comment]
The deployed site has some weird bugs when a user isn't signed in. At least there's plenty of stuff to work on..

**Comment by dummied** [comment]
That's the attitude!
