### ISSUE TITLE
Week 6, Day 3 - death to reddit - <Alec Martin>

### ISSUE THREAD

**Issue by captainclutch96** [tiy-indianapolis-ror-june2015/assignments#224]

**Comment by captainclutch96** [comment]
Could not figure out how to order links by votes, but fixed seeds.rb file, explained private method in links controller, and attempted to add glyphicons.
https://github.com/captainclutch96/redditclone/
https://secure-inlet-3388.herokuapp.com

**Comment by dummied** [comment]
The `cached_votes_total` column mentioned under "Caching" in the `acts_as_votable` README seems like a likely direction to look at for that.
