### ISSUE TITLE
Week 6 Lab -- Microblogging Social Network (Twitter) -- Andrew Riley

### ISSUE THREAD

**Issue by andrewariley87** [tiy-indianapolis-ror-june2015/assignments#230]
- [x] Users can signup, and sign in
- [x] User can follow other users
- [x] User can see posts from [User + Friends] in their Timeline
- [x] User can Post posts
- [x] Posts should be no more than 170 characters long
- [x] User can unfollow a person
- [ ] Site should look nice
- [x] Posts should be paginated
- [x] Data should be seeded (use faker) with at least 1000 toots and 100 users
- [x] Get live and up and working on Heroku

**Comment by dummied** [comment]
Links?

**Comment by andrewariley87** [comment]
my fault

**Comment by andrewariley87** [comment]
https://cryptic-refuge-4036.herokuapp.com/
https://github.com/tiy-indianapolis-ror-june2015/AndrewJoe-Week6Lab
