### ISSUE TITLE
Week 3 Lab (Redux)

### ISSUE THREAD

**Issue by captainclutch96** [tiy-indianapolis-ror-june2015/assignments#235]

**Comment by captainclutch96** [comment]
https://github.com/captainclutch96/Week-3-Lab-redux/tree/dev

Unfinished, but needed sleep.

**Comment by dummied** [comment]
Doesn't need to be completed in a single day. Keep working on it tomorrow. 

And get your sleep. Highly recommended. 

We'll review what you have so far right after lecture tomorrow.

**Comment by captainclutch96** [comment]
@dummied I took a stab at bootstrapped CSS, but I couldn't quite figure it out. 

However, I completely refactored my HTML code and checked it on the HTML validator site to make sure there were no errors. Also, when I got home, I added more containers to the code so that it could be sectioned off into columns. 

I also added an images folder, containing all of the images I intend to use for the page.

#progress

https://github.com/captainclutch96/Week-3-Lab-redux/tree/dev

**Comment by captainclutch96** [comment]
@dummied 

https://github.com/captainclutch96/Week-3-Lab-redux/tree/dev
