### ISSUE TITLE
Week 8, Day 2 - Testing - Danny Beyrer

### ISSUE THREAD

**Issue by beyrerdn** [tiy-indianapolis-ror-june2015/assignments#273]
# Deliverables

A pull request to your Week 7 Lab repo from branch testing to master
A comment on your original Issue with a link to your live, updated Heroku app and the aforementioned PR
Said issue assigned to Chris
# Requirements
# Normal Mode
- [ ] During the afternoon, I'll be making comments/issues against your weekend lab. Fix said issues.
- [ ] If you haven't completed all the modes of the past two assignments (Week 8, Day 1 and the Week 7 Lab), keep working on them.
- [x] Add tests for your models using shoulda
# Hard Mode
- [ ] Refactor your controllers to move methods into the models.
- [x] Make sure you have tests for them.
- [x] Get capybara and poltergeist installed.
# Nightmare Mode
- [ ] Write an integration test, ideally for sign up, login and/or logout

**Comment by beyrerdn** [comment]
Integration tests written, but did not properly add the poltergeist driver.
@dummied

**Comment by beyrerdn** [comment]
https://github.com/beyrerdn/In-a-Giffy/pull/18

https://serene-inlet-4786.herokuapp.com/ (cannot merge to heroku master in order to update app and add seed file)

@dummied

**Comment by dummied** [comment]
@beyrerdn `git pull heroku master`
